# Generated by Django 5.2.12 on 2026-09-29 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="office",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="office",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
