# Generated by Django 5.2.12 on 2026-09-26 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('certification_number', models.CharField(db_index=True, max_length=64)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('license_plate', models.CharField(max_length=20)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='fleet.office')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_on', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='fleet.maintenancetype')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='fleet.mechanic')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='fleet.vehicle')),
            ],
            options={
                'ordering': ('-performed_on', '-pk'),
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['office', 'active'], name='fleet_veh_off_act_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('license_plate',), name='uniq_active_vehicle_plate'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['vehicle', '-performed_on', '-id'], name='fleet_mr_veh_perf_id_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['performed_on'], name='fleet_mr_perf_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['mechanic', 'performed_on'], name='fleet_mr_mech_perf_idx'),
        ),
    ]
