# Generated by Django 5.2.12 on 2026-09-29 17:19

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0001_initial"),
        ("offices", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("vin"),
                name="unique_vehicle_vin_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("license_plate"),
                condition=models.Q(("active", True)),
                name="unique_active_vehicle_plate_ci",
            ),
        ),
    ]
